#ifndef Z_TPGRUPAL_BUILDINGSENUM_H
#define Z_TPGRUPAL_BUILDINGSENUM_H

enum class BuildingsEnum {
    FORT,
    FORT_DESTROYED,
    VEHICLE_FABRIC,
    VEHICLE_FABRIC_DESTROYED,
    ROBOT_FABRIC,
    ROBOT_FABRI_DESTROYED
};

#endif //Z_TPGRUPAL_BUILDINGSENUM_H
